### ISSUE TITLE
When i run the script, it is iterating the same URL multiple times (approx 38-40 times)

### ISSUE THREAD

**Issue by srinivasskc** [testautomationcookbook/CrawlSitemapXML#1]
When i run the script, it is iterating the same URL multiple times (approx 38-40 times)

How to make it run only once and verify the URL is working or not?

**Comment by testautomationcookbook** [comment]
the URL should not iterate itself but it first hit sitemap.xml page once and then hit all the urls of sitemap.xml once. in your case, can you please validate what all urls are there in your sitemap.xml? 

In case you still find some issue with the script, please send me the _**SimpleDataWriter.csv**_ output file to analyze the issue.

**Comment by srinivasskc** [comment]
Please share the email address, i will share the file.

**Comment by testautomationcookbook** [comment]
you can also attach the file here in comment or send it over to my email _prshah_prshah@yahoo.co.in_

**Comment by testautomationcookbook** [comment]
The script is not reiterating itself but it was logging info related to resource requests which will be labelled with the main url. To Disable the log of resource url you can go to Listener and click on Configure button. on the next dialog, deselect 'Save Sub Results' checkbox. now run the scripts again and you will see only main urls log.
![image](https://user-images.githubusercontent.com/74654135/102343089-21e72800-3fc0-11eb-99c8-3a1422998918.png)
